### ISSUE TITLE
大佬好，可否去除点进视频时出现的控制按钮（后退前进15秒，暂停按钮）

### ISSUE THREAD

**Issue by r0usan** [xiaye13579/BBLL#10]
可否去除点进视频时出现的控制按钮（后退前进15秒，暂停按钮）将控制按钮改成遥控器快进快退，OK键确定播放。

让菜单键也可以唤醒视频的控制面板。

按遥控器下键出现控制面板，其中有一个箭头，按下可以看到其他推荐视频。可否将这一步省略，按了下键或菜单键，出现控制面板后，再按一次下键，就直接进入推荐视频，直观。

**Comment by xiaye13579** [comment]
好的，有空会对遥控器做一套控制ui。

**Comment by xiaye13579** [comment]
新版做了一套新的播放器ui，可以试试

**Comment by r0usan** [comment]
dalao能不能一进视频就播放，不要弹出控制UI了
dalao能不能把推荐视频放到视频下方，按一次下出现控制UI，再按一次进入推荐页面
dalao一定很想知道这怎么想出来的，好吧，我坦白，YouTube就是这么控制的，很方便……
