### ISSUE TITLE
求求你！求求你！把 “弹幕开关选择” 放到下方的快捷按钮中

### ISSUE THREAD

**Issue by SpringGong** [xiaye13579/BBLL#1003]
首先感谢 Xiaye13579 为大伙儿提供这么好的APK，让我们在电视机大屏幕上也能流畅观看小破站的视频。

现在来说问题：自从升级到最新版本后，**弹幕开关**这个常用的键被放到了设置菜单里面，导致用电视机遥控器操作起来特别不方便，要走好远的路，到家的时候，连妈都不认识了 :-(

### **一、弹幕开关**
有些时候打开一些热门视频，满屏都是弹幕，根本就看不清视频内容。
这时，我得在遥控器上面按 21 次，才能完成关闭弹幕的操作：

- 1. 按遥控器向下键，此时光标停留在暂停播放上，
- 2. 按右键，到设置主菜单按钮，
- 3. 按OK键，打开设置主菜单，此时光标停留在最上面的“画质”
- 4 - 9：然后接连按 6 次向下键，光标才到弹幕设置
- 10. 按OK键，进入弹幕设置，此时，光标停留在最下方“允许底部悬停弹幕”
- 11 - 16：然后接连按 6 次向上键，光标才到弹幕开关这里
- 17：按OK键，进入弹幕开关，此时光标停留在“开”上面
- 18：按向下键，光标到“关”
- 19：按OK键，才把弹幕关掉
- 20-21：这还没完，整个设置的窗口还显示在那里，我得连按 2 次返回按钮，才能返回视频观看屏幕

您可以自己在电视机上面试一试，真的这个操作步骤太多了，求求你把这个  弹幕开关 放到下面的快捷按钮中

十分感谢！

**Comment by lieta-king** [comment]
这个关弹幕的快捷按钮本来就有好吧，而且改版后一直就存在，不过要手动打开，好像在设置里面播放设置里还是弹幕设置里，你都试试，记不太清了，遥控器按住向下，翻到最下面有一个弹幕开关，注意没有滚动条，总之一直翻到最下面，打开回到视频播放界面就能看到了，好像在播放/暂停键的后两个的位置上会多出一个弹幕按钮，你打字这么多，也不多翻翻设置啊！

**Comment by SpringGong** [comment]
@lieta-king，

十分感谢您的回复！请问您家电视上面是最新版 1.4.9吗？
我今天又把BBLL里面所有的菜单选项检查了一遍，都没有找到你所说的设置。

不知是否能麻烦您，告诉我确切的位置，或者拍一张照片发上来？

再次感谢！

**Comment by lieta-king** [comment]
![image](https://github.com/xiaye13579/BBLL/assets/133792627/fcf06403-872b-4cc3-8689-60e9d6f37571)
我是用的1.4.9版，安卓4和安卓5以上版本都用过，都是可以的。
左边最下面那个齿轮⚙️按钮（左下角）就是了，打开它，之后在左边一列选”播放设置”，后，右边一列，按住遥控器下，最下面一个就是弹幕开关了
![image](https://pics6.baidu.com/feed/a044ad345982b2b7a87a4ff8b5a0fbe376099b3a.jpeg)

**Comment by SpringGong** [comment]
@lieta-king 太感谢了，原来在主页的这个设置里面。我一直在视频播放页面去找，所以没有找到。

再次感谢，今天回家去设置一下。

**Comment by lieta-king** [comment]
OK

**Comment by SpringGong** [comment]
在BBLL主页左下角的设置按钮里面，找到了弹幕开关的设置，十分感谢@lieta-king
