### ISSUE TITLE
当前版本无法调整视频音量和观看视频评论

### ISSUE THREAD

**Issue by helGayhub233** [xiaye13579/BBLL#1030]
我的设备：Quest 3 VR(v67版本)一体机，安卓系统

问题描述：尝试过安装商店的官方版本和官方好的版本打开会崩溃闪退，目前这个第三方应用很好的解决了我在VR上安装B站客户端导致闪退的问题

优化建议：目前应用暂时无法对视频的大小音量进行调整，希望开发者能考虑增加一个按钮来调整音量以及视频评论按钮

**Comment by hokuto1102** [comment]
这个是电视端使用的，你家电视没音量调节的么？

**Comment by helGayhub233** [comment]
你是开发的爹是吧，还用你说？
