### ISSUE TITLE
建议快进快退按钮的功能和默认控件的调换一下

### ISSUE THREAD

**Issue by macshen** [xiaye13579/BBLL#105]
现在默认控件是按视频百分比（可能）跳跃的，
快进快退是固定的15秒、5秒，能否把这两项功能调换一下。应为平时用的时候大部分时间是小的时间线的跳跃。如果遇到长时间的视频，才会用到按百分比跳跃的功能。

**Comment by xiaye13579** [comment]
👌后面会改进下
