### ISSUE TITLE
能不能在播放界面加一个弹幕开关

### ISSUE THREAD

**Issue by silkwing** [xiaye13579/BBLL#1067]

**Comment by ljyhfs** [comment]
这功能必须有啊，现在每看一个视频都必须摁大约10次按键才能关弹幕。

**Comment by hairixinye** [comment]
不是有了吗

**Comment by silkwing** [comment]
> 不是有了吗

没有一键关闭的，无论是官方网页还是客户端，都能点一下关闭弹幕，到bbll要到下两级菜单里关闭，像我这种频繁开关弹幕的人就很崩溃

**Comment by hairixinye** [comment]
在播放设置中开启显示弹幕就可以了

**Comment by silkwing** [comment]
> 在播放设置中开启显示弹幕就可以了

我觉得你可能不是B站的重度用户，很多人的观看习惯是，有时想看弹幕，有时看到弹幕不友好或涉及剧透，就会关掉，但现在关一个弹幕至少要按十几次遥控器，很不方便，我觉得它应该在一级菜单

**Comment by hairixinye** [comment]
我的意思是播放设置底下有个显示弹幕开关按钮打开后在视频播放时按下会有弹幕图标点击即可开关弹幕

**Comment by silkwing** [comment]
> 我的意思是播放设置底下有个显示弹幕开关按钮打开后在视频播放时按下会有弹幕图标点击即可开关弹幕

感谢，即便你告诉我，我还是找了十分钟才找到这个开关，真想不通这么实用的功能，连开关都藏这么深

**Comment by silkwing** [comment]
Problem solved.
