### ISSUE TITLE
[优化] 4k电视上缩略图清晰度欠佳

### ISSUE THREAD

**Issue by glm9412** [xiaye13579/BBLL#120]
猜测读取的是移动端的封面图片，导致在电视上不够清晰，能否解决这个问题。可否检测到是电视的时候，封面图片的源替换成云视听小电视的版本

**Comment by xiaye13579** [comment]
主要为了照顾内存小的设备，有需求的话后续我可以加个高清图的选项。

**Comment by glm9412** [comment]
感谢大大付出，选项的话，希望弹幕描边也能提供开关，此外弹幕有时会出现模糊的现象，不知是否是偶发现象。
