### ISSUE TITLE
1.23版本中番剧类影片依然存在的播放bug

### ISSUE THREAD

**Issue by redraiderj** [xiaye13579/BBLL#134]
首先非常感谢在这个版本中加入了番剧和影视功能！原来之前那些搜索不到的影片是因为属于番剧和影视类😂
不过之前一直存在的播放bug经测试还存在：播放了剧集中的一集之后，如果通过选集菜单选择其他集，那么开始播放之后其实播放的仍然是之前那一集。但是如果启用连续播放视频，并选择当前列表，那么播放完这一集之后会正常播放下一集(虽然第一次启用这个选项时不会即时生效，要退出应用再进才可以连续播放)。如果能修复这个bug的话番剧和影视功能应该就基本完善了。

**Comment by xiaye13579** [comment]
了解了，之前没发现这儿也有问题。
