### ISSUE TITLE
播放界面交互逻辑修改建议

### ISSUE THREAD

**Issue by redraiderj** [xiaye13579/BBLL#144]
软件似乎是以Pad为基础设计的交互，作为电视用户，有些地方总感觉有些不太顺手，我有几点不成熟的建议，作者可以看看有没有参考价值。
1. 进入播放时播放控制条总是默认显示，需要按一下返回键才会消失，不知道可以不可以默认进入播放界面时隐藏控制条？毕竟点进视频的目的基本都是为了第一时间观看，感觉除了已经播放过一部分或者全部播放完了的视频在进入时可以显示控制条方便快进快退，从未播放过的视频进入时应该都可以默认隐藏的。
2. 随着功能的增加，现在控制条里的按钮也越来越多了，有没有可能把常用的几个单独拿出来，比如弹幕开关、画质选择、编码选择等少数几个放在右侧弹出栏，长按菜单键(或者Pad上长按屏幕)弹出，方便快速修改。然后现在按下键可以呼出控制条，能不能在呼出控制条之后再按下键呼出推荐视频/相关视频列表？其他的商业视频软件似乎都有类似的操作逻辑。
3. 现在左侧的导航区和上方的标签页如果用电视遥控器操作的话有一些麻烦，比如如果进入了分区部分，然后选了一个比较靠右的分区，再想切换到导航区时必须一路按左重新回去，比较麻烦。我理解如果是Pad的话直接手指点一下就好，但是电视遥控器不知道怎样做到。

**Comment by xiaye13579** [comment]
👌
