### ISSUE TITLE
希望各位不要在任何地方宣传此应用

### ISSUE THREAD

**Issue by yushunqwq** [xiaye13579/BBLL#157]
希望各位不要在任何地方宣传此应用，在其他地方发现此行为，可以顺手点个举报

**Comment by 2496414612** [comment]
不在站内宣传就行，其他位置应该还是可以的，要是完全不宣传 ，你也不会知道这个软件，反正我目前已经在吾爱破解论坛发了帖子介绍本软件了，阅读量已经破万了，目前排行榜第二，还在持续增长中，因为才刚发几天

**Comment by yushunqwq** [comment]
> 不在站内宣传就行，其他位置应该还是可以的，要是完全不宣传 ，你也不会知道这个软件，反正我目前已经在吾爱破解论坛发了帖子介绍本软件了，阅读量已经破万了，目前排行榜第二，还在持续增长中，因为才刚发几天

我刚才看了一下，确实是第二，可惜我没有吾爱破解的账号，看不了帖子，下回吾爱破解开放注册我一定要去注册个账号

**Comment by yushunqwq** [comment]
设置了阅读权限这点好评

**Comment by snowman** [comment]
这个客户端原来是开源的吗? 现在只有 `README.md` 文件了
