### ISSUE TITLE
字幕和历史模块问题

### ISSUE THREAD

**Issue by jmoorev** [xiaye13579/BBLL#16]
1.字幕占屏比为1/4时，字幕滚动会出现闪动和乱码
2.历史记录不能及时更新，只有在app下次启动时才更新

**Comment by xiaye13579** [comment]
目前点击左侧的图标也可以刷新当前页面，之后会优化

**Comment by jmoorev** [comment]
> 目前点击左侧的图标也可以刷新当前页面，之后会优化

试了可以刷新了，哈哈。升级1.0.8弹幕占屏比1/4时弹幕闪动问题也解决了。
还发现一个问题，https://b23.tv/4k4htg2 https://b23.tv/r2Zjw39 观看这两个视频app会闪退。
