### ISSUE TITLE
请问您对BBLL对外的传播是否在意？

### ISSUE THREAD

**Issue by linanqwq** [xiaye13579/BBLL#161]
像另一个哔哩哔哩第三方tv客户端BV因为过于传播，已经停止了对中国大陆的支持。
我并不是不希望不分享使用，是不希望走一样的路，以前的bilibilitv版就是树大招风。
现在在百度贴吧里的bilibilitv吧内已经吵起来了，基本在讨论BBLL在bilibili.com的传播。
请问您对这种传播是否反感？
(相关链接
【三分钟，只要三分钟，永久改变你刷B站方式，如果没改变当我没说~~~-哔哩哔哩】 https://b23.tv/0HwJqTp
bilibilitv吧:http://tieba.baidu.com/wxf/26633891?kw=bilibilitv&fr=sharewise&sfc=qqfriend&client_type=2&client_version=12.30.1.0&st=1673919834&is_video=false&&source=12_16_sharecard_a

**Comment by xiaye13579** [comment]
我在意也没用啊

**Comment by nanmulifeng** [comment]
bv翻一下墙进去后
关闭翻墙软件
可以正常使用
或降级

优秀的软件被传播是很正常的
但我们也阻止不了他们传播啊
