### ISSUE TITLE
希望增加遥控器的几个常用按钮交互

### ISSUE THREAD

**Issue by neoworld** [xiaye13579/BBLL#178]
您好，播放时能加上跳转到下一个视频的按钮吗？很多安卓遥控器都有这个按钮，还有快退快进，望支持！这样不喜欢的就可以一键直接跳过了!

btw:现在BBLL体验远远超过官方和ATV上的Miao Project了，加油！苹果遥控器就喜欢精简这些按钮，我觉得很不人性化！

**Comment by xiaye13579** [comment]
我家电视也没那么多按键，下版我先加上支持，不敢保证可以用。😂

**Comment by neoworld** [comment]
> 我家电视也没那么多按键，下版我先加上支持，不敢保证可以用。😂

感谢，这几个键的键值在各大操作系统（安卓苹果win/linux）里都是统一的,以前多媒体键盘上的就是

**Comment by neoworld** [comment]
看到了1.2.7的更新，跳转按钮测试可以用了
