### ISSUE TITLE
杜比视界问题

### ISSUE THREAD

**Issue by AdivonL** [xiaye13579/BBLL#181]
由于杜比视频还非常少见，问题优先级较低：

1. 播放杜比视界视频无法点亮杜比视界；
2. 接1，由于电视未识别到杜比视界格式，色彩、亮度显示错误，发绿发紫发灰；
3. 切换AVC/HEVC/AV1无法解决该问题。

测试视频：杜比演示片（https://www.bilibili.com/video/BV1eV411W7tt/）
设备：索尼XR-65X91J（4K，4核A73，安卓10）
 

仅供参考：以上问题在使用小电视投屏的时候也会发生，清晰度变为4K；其他应用诸如KODI也出现过；偏色除了发绿发紫发灰，在其他app的片源还有过在颜色正常的基础上饱和度溢出，发红发青，非常赛博朋克，原因不明。

感谢大佬带来这么好用的TV浏览器

**Comment by xiaye13579** [comment]
下一版我会加上支持，才发现杜比视界有特有的视频编码。

**Comment by xiaye13579** [comment]
而且avc编码最大仅支持到4k。

**Comment by lightyear2023** [comment]
我的电视是支持杜比世界的，但是开了杜比世界模式和4k好像没什么区别
