### ISSUE TITLE
希望适配一个api18 

### ISSUE THREAD

**Issue by jayjd** [xiaye13579/BBLL#182]
家里电视是乐视Android4.3的
希望作者大大 适配一下 谢谢
@xiaye13579 
@xiaye13579 
@xiaye13579

**Comment by BLdada** [comment]
不可能的
这个客户端最低仅适配API 19也就是Android 4.4，如果适配4.3就会有很多库不兼容
而且这个软件不开源，适配看作者意愿

**Comment by nanmulifeng** [comment]
建议换一个也不贵
且4.4就不太好写了
4.3就更不要说了

**Comment by jayjd** [comment]
> 

4.4和4.3 差别不大吧

**Comment by chinatengjie** [comment]
100 买个移动电视盒子好了

**Comment by jayjd** [comment]
@BLdada @nanmulifeng @chinatengjie  之前的哔哩哔哩弹幕版支持到了 api17 应该是android4.2

**Comment by jayjd** [comment]
close

刚买了小米盒子 感谢作者的软件 不用适配了

**Comment by vpw2011** [comment]
现在确实买了一个便宜的安卓盒子用在，一样是乐视电视，还是希望有机会大佬能适配一下安卓4.3A PI18。先谢了。
