### ISSUE TITLE
1.2.6 历史记录里播放视频退出后光标定位问题

### ISSUE THREAD

**Issue by i007x** [xiaye13579/BBLL#186]
TV端，遥控操作，从历史记录列表播放任意视频，结束后退出，光标错误定位到左上角“搜索”上去了，

另外希望优化一下“从历史记录列表播放任意视频，结束后退出”，光标能保留在当前位置，而非前几个版本的回到顶部（第一个视频）上，不然想看几个历史视频要一下往下点很久

谢谢大佬

**Comment by wjz60** [comment]
第二个我反馈过，作者已经答应会优化了#122

**Comment by drw2005** [comment]
是的，第一个问题确实存在。

**Comment by xiaye13579** [comment]
好的，我检查下

**Comment by i007x** [comment]
1.2.7已修复，感谢作者🥰
