### ISSUE TITLE
几个小bug

### ISSUE THREAD

**Issue by sggc** [xiaye13579/BBLL#19]
大佬辛苦，貌似只能点赞，不能取消。
有个视频点开就闪退，这是视频链接https://b23.tv/AW7zE14
还有打开点赞界面与分p视频列表的时候能不能让视频继续播放
辛苦

**Comment by sggc** [comment]
对了，还有一个小bug，手机上看过的专栏文章在bbll的历史记录里会出现

**Comment by xiaye13579** [comment]
多谢反馈

**Comment by sggc** [comment]
专栏文章在历史记录出现已修复
老视频闪退问题已修复
其余两项应该暂无规划
