### ISSUE TITLE
关于收藏夹封面图

### ISSUE THREAD

**Issue by yushunqwq** [xiaye13579/BBLL#190]
本来收藏夹封面图片应该会随着新收藏视频的封面变化的，但是现在收藏夹的封面却始终是当时我刚登录时收藏视频的封面

**Comment by 1234fghj** [comment]
有些视频会黑屏，看番的时候下面会出现source error

**Comment by yushunqwq** [comment]
> 有些视频会黑屏，看番的时候下面会出现source error

你可以看一下，下面其他人提出的相同问题的解答：https://github.com/xiaye13579/BBLL/issues/183
