### ISSUE TITLE
新版本还是无法登录

### ISSUE THREAD

**Issue by fryccer** [xiaye13579/BBLL#20]
电视端扫码后，依旧显示无登录状态。

**Comment by xiaye13579** [comment]
登陆完成后直接退出app重进试试。或者试试在网页上扫码登陆一下看看，有时候登陆次数太多会账号会进入异常状态，要收一下手机验证码解锁。

**Comment by fryccer** [comment]
登陆完成并退出重新试了很多次，还是不行。网页扫码显示正常。

**Comment by fryccer** [comment]
1.0.9依然无法登录，电视雷鸟R645c，安卓9.

**Comment by NishimiyaShouran** [comment]
加一

**Comment by douginwai** [comment]
+1 极米投影仪z6x

**Comment by xiaye13579** [comment]
大致明白原因了，大家再试试1.1.0的版本。

**Comment by NishimiyaShouran** [comment]
好嘞这就去试试

**Comment by NishimiyaShouran** [comment]
> 大致明白原因了，大家再试试1.1.0的版本。

能登上了，感谢感谢

**Comment by fryccer** [comment]
能登陆了，感谢
