### ISSUE TITLE
 CC字幕咋没了

### ISSUE THREAD

**Issue by 20080919** [xiaye13579/BBLL#204]
刚突然发现视频的CC字幕怎么没了
望作者修复

**Comment by yushunqwq** [comment]
cc字幕移动到了选择画质那里

**Comment by 20080919** [comment]
好的谢谢












达瓦里氏
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月20日(周五) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaye13579/BBLL]  CC字幕咋没了 (Issue #204)




 
cc字幕移动到了选择画质那里

**Comment by 20080919** [comment]
谢谢大佬问题已解决
