### ISSUE TITLE
希望大佬可以加入评论区功能

### ISSUE THREAD

**Issue by wyza666** [xiaye13579/BBLL#207]
希望大佬加入评论区功能，这样的话BBLL的互动性就更高了
望大佬参考
谢谢大佬
新年快乐

**Comment by Aaronliu778** [comment]
个人觉得意义不大，电视上打字很麻烦。

**Comment by java30433** [comment]
主要不是评论而是看评论

**Comment by redraiderj** [comment]
我也觉得意义不大，电视上还是以看视频为主，光看评论不能回复不也很蛋疼吗？还不如直接用手机

**Comment by stephen-cusi** [comment]
有一定必要，可以增加一个开关，来控制是否展示评论区

**Comment by r0usan** [comment]
没有必要，投入产出比极低

**Comment by ZerOri** [comment]
> 我也觉得意义不大，电视上还是以看视频为主，光看评论不能回复不也很蛋疼吗？还不如直接用手机

有意义，有些视频就是想看看评论区一些高手解读加深理解。油管tv现在也有查看评论的功能。

**Comment by wyza666** [comment]
谢谢大佬，我决定还是不用加评论区功能了
