### ISSUE TITLE
搜索功能改进建议

### ISSUE THREAD

**Issue by redraiderj** [xiaye13579/BBLL#21]
点进搜索界面会调用电视默认输入法，我用的电视输入法很难用，也不支持按首字母搜索，如果能参考原来tv版的搜索方式就好了
![IMG_1215](https://user-images.githubusercontent.com/255464/208225316-6554e791-b174-4a91-91d8-ede3730d3cad.jpeg)

**Comment by ff522** [comment]
还可以加上搜索建议和  热门搜索

**Comment by androidcn** [comment]
希望能加入搜索历史
