### ISSUE TITLE
1.2.8播放部分视频刚开始播放时会卡顿几秒钟

### ISSUE THREAD

**Issue by KanzakiK** [xiaye13579/BBLL#239]
今天升级1.2.8后播放部分视频，刚开始播放时会先开始正常播放2秒，然后画面卡住大概3秒，然后才正常播放，画面卡住时声音是正常的。十分钟以上的长视频可能会遇到第二次卡顿。反复开始播放同一个视频可以复现这个卡顿，1.2.7时未遇到这种情况。

问题视频案例
https://b23.tv/8OrD6W3

**Comment by r0usan** [comment]
测了，未复现，我的设备是神盾盒子。可能是你盒子性能有点弱

**Comment by xiaye13579** [comment]
尝试换成切换默认视频编码试一试

**Comment by KanzakiK** [comment]
> 

刚退回两个老版本测试，一样复现，不过我确实记得这是最近出现的问题，看来跟我最近盒子刷的新版本slimbox固件有关，抱歉抱歉，谎报军情了，应该是我这边盒子的问题。
