### ISSUE TITLE
部分hevc编码视频闪退

### ISSUE THREAD

**Issue by kartyl** [xiaye13579/BBLL#242]
b站部分hevc编码格式为hev1.1.6.L120.90的视频会导致app闪退，比如：https://www.bilibili.com/video/BV1Fv4y1k71e/
hev1.1.6.L150.90编码可以正常播放

**Comment by r0usan** [comment]
啊叻？视频不见了？

点你的链接，出现上述文字

**Comment by kartyl** [comment]
> 点你的链接，出现上述文字

https://www.bilibili.com/video/BV1Fv4y1k71e/?share_source=copy_web&vd_source=0925f42e8f2b3b73f15e18085150e346

抱歉，重新发了链接

**Comment by r0usan** [comment]
还是一样{啊叻？视频不见了？}

**Comment by r0usan** [comment]
我懂了，不要点击跳转。复制到浏览器，然后可以打开。

**Comment by r0usan** [comment]
帮你测了，未复现bug。
操作系统：安卓11
设备：shield tv pro

**Comment by kartyl** [comment]
> 帮你测了，未复现bug。 操作系统：安卓11 设备：shield tv pro

我刚在手机上安卓13试了下也正常。
两台闪退的电视都是安卓5

**Comment by liyk123** [comment]
这个大概是因为编码不支持，然后异常没有处理

**Comment by kartyl** [comment]
> 这个大概是因为编码不支持，然后异常没有处理

试了下另一个播放器也是闪退，大概率就是你说的原因了，看来系统解码器支持不全面
