### ISSUE TITLE
【技术交流】想请教下，当前是如何将音视频合并在一起播放的？

### ISSUE THREAD

**Issue by cqm1994617** [xiaye13579/BBLL#248]
我看了下b站视频详情的接口，目前是将音视频分成video和audio这两个字段返回的。如我截图所示

![image](https://user-images.githubusercontent.com/13933287/215119645-fcb92ba1-fd90-497b-92f2-7d29301c0439.png)
视频字段里的那个文件是没有声音的。

请问下现在BBLL这个应用中，是如何把音频合入视频中的？
还是说暂时没有这个步骤(看到首页wiki中似乎提到暂时没有软解？而且看包体积很小，感觉也没引入ffmpeg之类的类库)，只是单纯同时播放音频和视频的m4s文件并且手写代码保证时间上基本同步？

本人并非专门的音视频/安卓方向开发，只是对此比较好奇想了解下当前方案。如能回复，非常感谢~另祝新年快乐

**Comment by xiaye13579** [comment]
我这用的谷歌的exoplayer，功能比较强大，默认是硬解，我没集成别的解码器。其中MergingMediaSource可以联合播放音频和视频，如果不用exoplayer那也只能用ffmpeg了。

**Comment by cqm1994617** [comment]
> 

非常感谢解答~
