### ISSUE TITLE
部分杜比视界视频无法正常点亮

### ISSUE THREAD

**Issue by jjijack** [xiaye13579/BBLL#262]
目前BBLL版本为1.2.9，播放设备为英伟达shield，安卓版本11.

已经能够成功点亮部分杜比视界视频，例如该视频：https://www.bilibili.com/video/BV1ud4y197zt ，杜比视界与杜比全景声都可以正常播放。
![610987F7-8FEC-4DF1-8A92-4C0529BFB4D4](https://user-images.githubusercontent.com/32895850/215310767-dd848643-f8e4-44d9-a8ad-9f8a8458e9bf.jpeg)

但部分杜比视界视频无法正常点亮，例如该视频：https://www.bilibili.com/video/BV1zv411w7Aj 。
![F188BEF0-2CE9-4190-98BE-ED65D07E3943](https://user-images.githubusercontent.com/32895850/215310770-ea555217-e35d-49aa-b977-c8bec8b6a66b.jpeg)

所有杜比视界视频的清晰度都能选择Doldy Vision，但是能点亮的视频编码里可以选HEVC Doldy Vision，不能点亮的视频编码里没有它，只能选择HEVC，通过h265而不是DOVI解码器解码。

希望作者能够修复这个问题。尽管存在这个bug，这也是我用过最好的在电视上看B站杜比视界的软件了，感谢作者大大。

**Comment by 8884361** [comment]
这个或许不是BBLL的Bug
DV有几种做法，Profile 5，Profile 8.4 ，BL+RPU
我垃圾索尼Z9D只能吃Profile 5，
Profile 8.4当HLG处理了。
最后一种压根连HDR都没法激活。

**Comment by xuhuanxxx** [comment]
profile 5: https://www.bilibili.com/video/BV1eV411W7tt/
profile 8: https://www.bilibili.com/video/BV17b4y177DG/

你再看看这俩能不能正常播放，尤其是profile 5是蓝的还是绿的

**Comment by jjijack** [comment]
> profile 5: https://www.bilibili.com/video/BV1eV411W7tt/ profile 8: https://www.bilibili.com/video/BV17b4y177DG/
> 
> 你再看看这俩能不能正常播放，尤其是profile 5是蓝的还是绿的

升级1.5.0版本后都能够正常播放了
