### ISSUE TITLE
低安卓版本希望可以兼容

### ISSUE THREAD

**Issue by Kataomoiii** [xiaye13579/BBLL#28]
安卓4.4安装失败

**Comment by wangking13** [comment]
这个APP 设计时应该就没考虑低版本安卓··别说安卓4.4了··安卓7 都无法正常运营这个APP··实测必须安卓9 才行··安卓4.4 太老了··最近出的几个第三方B站APP··基本都不支持安卓4.4，隔壁的BV也是··你还是换设备吧·舍不得换电视机的话，就买个一百多的盒子

**Comment by chenjiev5** [comment]
> 这个APP 设计时应该就没考虑低版本安卓··别说安卓4.4了··安卓7 都无法正常运营这个APP··实测必须安卓9 才行··安卓4.4 太老了··最近出的几个第三方B站APP··基本都不支持安卓4.4，隔壁的BV也是··你还是换设备吧·舍不得换电视机的话，就买个一百多的盒子
安卓6的电视安装成功

**Comment by tallguess** [comment]
我极米投影仪也是4.4.2，安装提示解析包错误，小米电视4a，6.01的1.11版本可以安装使用了

**Comment by xiaye13579** [comment]
1.1.6提供了4.4可用的版本
