### ISSUE TITLE
小米电视4a，1.3.0解析包错误

### ISSUE THREAD

**Issue by tallguess** [xiaye13579/BBLL#317]
小米电视4啊，安卓6，1.2.7正常安装使用，后续版本安装都提示解析包错误，望新版本能兼容一下
![Uploading 899FFFAF-FD92-417D-AA97-8E23EB8A7E0D.jpeg…]()

**Comment by yyj1145141919810** [comment]
我的也是4a，那我的为啥没问题呢？

**Comment by tallguess** [comment]
1.2.7都正常安装，往后版本一直到1.3.1都无法安装，不知道有什么区别

**Comment by yyj1145141919810** [comment]
断网安装试一下呢












达瓦里氏
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月11日(周六) 晚上11:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaye13579/BBLL] 小米电视4a，1.3.0解析包错误 (Issue #317)




 
1.2.7都正常安装，往后版本一直到1.3.1都无法安装，不知道有什么区别

**Comment by tallguess** [comment]
用安卓重签名工具重新签名后可以安装使用了！
