### ISSUE TITLE
[BUG] BBLL V1.30 API19版本，登陆后不能播放投稿视频！

### ISSUE THREAD

**Issue by hitori-Janai** [xiaye13579/BBLL#320]
排查后发现未登录时可以播放投稿视频。
登录后无法播放投稿视频，但可以流畅播放直播，影视很卡顿。

播放投稿视频时黑屏报的`调试信息`，屏幕不停转圈等待，进度条也有加载。
```
Video : Format(1, null, null, video/avc,avc1.640032,-1, null,[1080,1920,-1.0],[-1,-1])
Audio : Format(2, null, null, audio/mp4a-latm, mp4a.40.2,103239, und,[-1,-1,-1.0],[2,44100])
VideoCodec : OMX.MTK.VIDEO.DECODER.AVC
Audiocodec : OMX.MTK.AUDIO.DECODER.AAC
```
TCL广告机，不清楚具体配置。
这个问题出现很久了，前几个版本也有这种情况

**Comment by XiaoJunwen18** [comment]
**和你的问题相同，但作者没有回复**

**Comment by hitori-Janai** [comment]
```
CPU     MT5882
设备    MTK Generic Android on mt5882
系统    Andrald4.4.3 API19
分辨率  1920x1080
```
如上是更新新版本查看到的硬件信息 
希望有空你能看看 @xiaye13579

**Comment by hitori-Janai** [comment]
[65元包邮2+16gb的魔百盒cm311-1a，这个电视盒有点真香](https://www.bilibili.com/video/BV1B14y1j7iV/?spm_id_from=pageDriver&vd_source=8a2eafc0887a5d380133056d358a0268)

@XiaoJunwen18  还是花点钱买个电视盒子，方便快捷。老旧电视不值得折腾

**Comment by hitori-Janai** [comment]
魔百盒 体验不错
