### ISSUE TITLE
1.31设置视频编码为AV1，播放时会默认使用AVC编码，1.30没有这个问题

### ISSUE THREAD

**Issue by fghp** [xiaye13579/BBLL#354]

**Comment by AdivonL** [comment]
我也发现了，而且设置完默认AV1之后退出再进设置，选项字样变成HEV1（记不清了）；
实际播放时窗口显示AVC，目前我切成默认HEVC了，暂时过渡一下。

**Comment by linxiazhixi** [comment]
是的，131设置视频编码改了，但是退出设置之后就还是变成hvc1了，没法保存编码更改
