### ISSUE TITLE
投硬币bug

### ISSUE THREAD

**Issue by wyza666** [xiaye13579/BBLL#379]
投硬币的时候，一直显示“非法投币数量”

**Comment by nanmulifeng** [comment]
我这会显示“非法访问”

**Comment by kamidou** [comment]
只有部分视频有这个问题，比如https://b23.tv/FcXDllq

**Comment by wyza666** [comment]
但是我看的大部分视频都有投币显示非法访问，以及硬币不足非法投币数量等等












达瓦里氏
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月23日(周四) 凌晨2:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaye13579/BBLL] 投硬币bug (Issue #379)




 
只有部分视频有这个问题，比如https://b23.tv/FcXDllq

**Comment by wyza666** [comment]
目前这个问题已经没有了，谢谢大佬
