### ISSUE TITLE
页面、封面、视频加载时延大，转圈圈1分钟以上

### ISSUE THREAD

**Issue by ych516** [xiaye13579/BBLL#389]
海美迪的盒子，6.0+的安卓系统，百兆电信宽带。
所有界面加载、视频列表的封面加载、视频加载都时延非常大。转圈圈1分钟以上。
这个是正常现象还是我的个案？

如果是个案的话，有什么优化配置的方式吗？

**Comment by btandylau** [comment]
光猫禁用ipv6试试？

**Comment by ych516** [comment]
> 光猫禁用ipv6试试？

果然就好了，现在大部分时延在3-5秒了，太感谢了！
