### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by zhxch3** [xiaye13579/BBLL#4]
三台不同安卓设备都尝试了，扫码后依旧提示登录

**Comment by xiaye13579** [comment]
我的设备太少了，也不好查什么原因，后续我会加入别的登录方式。

**Comment by zhxch3** [comment]
好的辛苦了，我试了下手机米10扫码也无法登录，表现为确认登录后二维码消失但是没有拉去到登录信息依旧提示登录

**Comment by zgy62681186** [comment]
我的雷鸟s535d也是无法登录

**Comment by xiaye13579** [comment]
新版本已修复
