### ISSUE TITLE
[Bug] 播放设置选择AV1编码无法保存

### ISSUE THREAD

**Issue by KinShin** [xiaye13579/BBLL#404]
进设置——播放设置——视频编码，选择AV1，退出设置，重新进入设置，查看播放设置的视频编码，显示的是“HVC1”，并未正确保存AV1的设置。（HVC1是什么鬼，选择菜单里没有这个编码）

**Comment by AdivonL** [comment]
此问题也存在于当前最新的1.3.2版本中，设置默认AV1之后，设置内会保存为HVC1，播放视频实际使用的是AVC

**Comment by KinShin** [comment]
1.3.3 版仍然存在这个问题

**Comment by KinShin** [comment]
1.3.7 已修复
