### ISSUE TITLE
1.3.3，1.3.2能不能在设置里加个选项，不要自动连续播放合集里的视频？

### ISSUE THREAD

**Issue by fghp** [xiaye13579/BBLL#425]
因为现在这个合集并不是up主在该条视频下设的分集，而是这个软件自己总结出的一个合集，所以连续播放经常会放一些不相干的视频，非常烦人。 
另外，1.31里视频解码设置av1的bug仍然存在。
只好用回1.3.0了。

**Comment by digitalbaka** [comment]
同问

**Comment by xelamai** [comment]
同需求。好像有播放列表的就一定会自动播放下一个，设置里设置“什么都不做”也没用，而且播放器的循环播放按钮每次都重置
