### ISSUE TITLE
详情页进UP视频列表会发生重复

### ISSUE THREAD

**Issue by macshen** [xiaye13579/BBLL#457]
在视频详情页面，点UP名字进他的视频列表页面，从第21个视频开始重复1-20个，原本的21-40没有列出来。

**Comment by Grouppppp** [comment]
动态页里也有重复。

**Comment by YiuTerran** [comment]
动态页大量重复…

**Comment by redraiderj** [comment]
1.3.5版仍然有这个问题，UP第21-40个视频和第1-20个重复
![IMG_1503](https://user-images.githubusercontent.com/255464/226100334-912740a0-8cf9-4f60-8f58-7cc876352af2.jpeg)
![IMG_1504](https://user-images.githubusercontent.com/255464/226100338-bdaf436b-53a6-41fa-9bf3-f89b0f3e0ce7.jpeg)

**Comment by macshen** [comment]
1.3.7 已修复，完结、撒花！
