### ISSUE TITLE
BUG: 设置页面中视频解码修改无法生效

### ISSUE THREAD

**Issue by BoilingBlues** [xiaye13579/BBLL#488]
1. 设置页面中将视频解码修改为AV1之后，退出设置页面再重新进入设置页面，视频解码变成hvc1
2. 视频播放页面中查看视频解码依然是avc，avc播放4k视频卡顿，手动在播放页面调整视频解码为AV1恢复正常

机器是s905x4，支持av1解码；安卓版本是11

**Comment by fghp** [comment]
这个是老问题了

**Comment by BoilingBlues** [comment]
1.3.7版本已被解决
