### ISSUE TITLE
无法正确显示时间。也无法正常播放

### ISSUE THREAD

**Issue by Aaronliu778** [xiaye13579/BBLL#52]
一共1个多小时，只能播放6分钟。剩下的没有了。时间也无法正确显示，

链接如下

![image](https://user-images.githubusercontent.com/95974146/209458734-a6eb4c19-fea3-4a39-8c41-e95eaa1ce592.jpeg)【《金星战记》 金星移民者们，为生存而战！-哔哩哔哩番剧】https://b23.tv/ep92421

**Comment by Aaronliu778** [comment]
实际时间![image](https://user-images.githubusercontent.com/95974146/209458745-1cc22158-1d34-473c-a940-a5edcf07e8a9.png)

**Comment by xfangfang** [comment]
这个是flv拼接的视频，大概是16年左右的视频使用了这样的方式。

提供一个非番剧视频供作者测试：https://www.bilibili.com/video/BV1dx411c7Av

**Comment by xiaye13579** [comment]
1.1.4版本会修复

**Comment by Aaronliu778** [comment]
可以关闭了大佬。放个捐助链接。> 1.1.4版本会修复
