### ISSUE TITLE
希望可以增加 稍后再看 的接口列表

### ISSUE THREAD

**Issue by xshwy** [xiaye13579/BBLL#53]
经朋友安利了这个客户端，使用了一段时间，是真的超级无敌非常好用，特别是可以看到自己关注列表的更新状态。

目前用的最多的一个是，稍后再看，希望作者可以加入更新

访问接口 https://api.bilibili.com/x/v2/history/toview/web 即可获取到完整的稍后再看列表

<img width="322" alt="image" src="https://user-images.githubusercontent.com/1038801/209460537-b0487ba5-25d0-4b39-a72c-60b9ab92ab29.png">

**Comment by xiaye13579** [comment]
👌

**Comment by xiaye13579** [comment]
1.1.4加上了
