### ISSUE TITLE
开启“连续播放推荐视频”之后如果在历史记录里点击已经播放完成的视频会迅速跳转至推荐视频并开始播放

### ISSUE THREAD

**Issue by redraiderj** [xiaye13579/BBLL#58]
如题，如果开启了这个选项之后点击历史记录里已播放完成的视频，因为记忆了播放位置，会直接跳转到视频结束处，然后迅速跳转至推荐视频开始播放，基本没时间回退进度条重新观看，只能关掉这个选项才行。

**Comment by xiaye13579** [comment]
收到，后续优化下。
