### ISSUE TITLE
对400x640分辨率的支持

### ISSUE THREAD

**Issue by maxesisn** [xiaye13579/BBLL#580]
设备型号：影目INMO Air2 (AR眼镜)
详细配置：
![screenshot_1684502800338](https://github.com/xiaye13579/BBLL/assets/20412597/8891105c-68d2-4304-bc2e-fd1517ed329e)
![screenshot_1684502808255](https://github.com/xiaye13579/BBLL/assets/20412597/63579c9e-f350-4a1d-ab31-06987f999d66)
当前界面适配情况：
![screenshot_1684502625898](https://github.com/xiaye13579/BBLL/assets/20412597/37460d6a-ac66-48a3-ae11-67df5866fc83)

**Comment by wanningfe** [comment]
像是系统DPI不对，应该把系统DPI调整一下就行了。

**Comment by maxesisn** [comment]
是的，检查发现是INMO OS使用了奇怪的DPI，但是修改的话又会导致系统界面比例不正常。
（如果项目开源，说不定就能搓一个影目专版了）
