### ISSUE TITLE
请检查视频调试信息显示是否正确

### ISSUE THREAD

**Issue by redraiderj** [xiaye13579/BBLL#59]
因为没有之前版本的截图，所以不是很确定是哪个版本引入的问题，但是现在视频调试信息似乎有些问题。如图所示，图一是Google Chromecast with Android TV，图二是索尼X8500G。
![IMG_1259](https://user-images.githubusercontent.com/255464/209565795-38a4e648-9b8d-4cc3-8601-369b8118187f.jpeg)
![IMG_1260](https://user-images.githubusercontent.com/255464/209565798-b76c55e9-913b-4f23-bbbb-5803a08a7264.jpeg)

**Comment by xiaye13579** [comment]
当时给测试编码选择用的，并没有特别优化过这个。😄
