### ISSUE TITLE
建议增加观看直播功能

### ISSUE THREAD

**Issue by zxc135781** [xiaye13579/BBLL#6]
大佬是否可以增加观看直播的功能？感谢！

**Comment by xiaye13579** [comment]
直播有点麻烦，还得试接口，优化播放器，之后看情况加吧。

**Comment by drw2005** [comment]
> 直播有点麻烦，还得试接口，优化播放器，之后看情况加吧。

大佬能考虑太好了，直播功能加上就完美了。

**Comment by xiaye13579** [comment]
新版本可以从历史记录里看直播

**Comment by drw2005** [comment]
> 新版本可以从历史记录里看直播

确实可以看了，感谢大佬！

既然历史纪录里能实现了，大佬可考虑把直播单独列出来？
