### ISSUE TITLE
再次恳请作者针对低版本安卓适配优化

### ISSUE THREAD

**Issue by wangking13** [xiaye13579/BBLL#61]
这个APP真的很不错· 但很多人的设备是安卓5以下，甚至是安卓4.4的。无法正常使用APP
请作者能够考虑加入对低版本安卓的适配··让更多的人可以用上这个好软件
目前实测，安卓6以下的智能电视，安卓7以下的电视盒子，都无法正常使用··或者就是异常退出

**Comment by OiCkilL** [comment]
+1，一般安卓电视的版本都不太高，确实需要多编译几个版本

**Comment by xiaye13579** [comment]
好的，有空安排下

**Comment by Labrador-QAQ** [comment]
安卓6的小米盒子4实测能安装
装上了低端芯片也没有流畅性

**Comment by Labrador-QAQ** [comment]
真的想好好用还是买一个外贸盒子吧

**Comment by wangking13** [comment]
> 



> 好的，有空安排下

好的  谢谢 您费心了····

**Comment by wangking13** [comment]
> 真的想好好用还是买一个外贸盒子吧

我5台电视 6个盒子···其实都能用··只不过朋友安卓版本低不能用··而且这种情况其实很普遍，所以等于是为大家提个ISSUE了

**Comment by xiaye13579** [comment]
1.1.6专门提供了一个4.4可用的版本，可以试试
