### ISSUE TITLE
希望可以调整一下主页等UI缩放问题

### ISSUE THREAD

**Issue by Hwenray** [xiaye13579/BBLL#615]
![EI8~D}M 0R~SB4~WCNADBWH](https://github.com/xiaye13579/BBLL/assets/65950462/a68b394f-e6b6-45ab-94fa-1609da5aca83)
![$J39{M~0_%ZML0UF1L8W U9](https://github.com/xiaye13579/BBLL/assets/65950462/4dcc541d-d00b-41d1-becc-ecbf8e0fa949)
![S)(T8I}@Q{M`GI(6FXZB}A5](https://github.com/xiaye13579/BBLL/assets/65950462/2a58db1c-8563-4df8-8a18-8922bca0b670)
如题，图，BBLL（逼逼赖赖（bushi））在我的OPPO Watch SE上显示错误，主页/设置均有缩放问题，希望可以调整一下，使主页/设置等界面随着设备DPI改变而缩放

**Comment by HWR20080716** [comment]
当前设备分辨率为327*430，DPI为160

**Comment by LBBear** [comment]
牛逼，在手表上用，上学你就好好学习，提这些奇葩需求

**Comment by HWR20080716** [comment]
> 

这也不奇葩吧（恼）
UI缩放有问题就不能提吗 :(

**Comment by HWR20080716** [comment]
> 牛逼，在手表上用，上学你就好好学习，提这些奇葩需求

这也不奇葩吧（恼）
UI缩放有问题就不能提吗 :(

**Comment by zhunxing358** [comment]
这货见人就咬 记得打疫苗

**Comment by refined-fish** [comment]
新版本应该已经解决此类缩放问题，没有相关设备无法测试，请自行测试

**Comment by Hwenray** [comment]
> 新版本应该已经解决此类缩放问题，没有相关设备无法测试，请自行测试

仍然无法正常缩放（可能是我设备分辨率太小了
