### ISSUE TITLE
不是issue，请教下安装的问题

### ISSUE THREAD

**Issue by holefrog** [xiaye13579/BBLL#651]
您好。您开发的这个软件比官方的好用，非常感谢。

有一个小问题想请教：我通过adb  install把app安装在sony电视上。其它adb安装的app，如chrome不能出现在电视机的app列表中，但你这个安装完就直接出现了，使用起来很方便。能告知如何做到的吗？用adb 命令能否把其它app也加到列表中。
先谢谢啦。

**Comment by xiaye13579** [comment]
应用启动方式分手机上的LAUNCHER和TV上LEANBACK_LAUNCHER，索尼的电视列表是显示LEANBACK_LAUNCHER，其他应用想显示得修改android_manifest.xml文件才行。

**Comment by holefrog** [comment]
原来是这样。非常感谢

Get BlueMail for Android<https://bluemail.me>
On Aug 5, 2023, at 7:01 a.m., xiaxiaoao ***@***.******@***.***>> wrote:

应用启动方式分手机上的LAUNCHER和TV上LEANBACK_LAUNCHER，索尼的电视列表是显示LEANBACK_LAUNCHER，其他应用想显示得修改android_manifest.xml文件才行。

**Comment by akssd** [comment]
既然回答完了，何不关闭这个issue?

**Comment by holefrog** [comment]
谢谢
