### ISSUE TITLE
一个光标元素遮挡全屏画面的问题

### ISSUE THREAD

**Issue by fox0517** [xiaye13579/BBLL#68]
当使用遥控器操作时，当前光标所在元素会有一个深粉色的半透明色块提示当前光标位置，这个本来是交互视觉辅助的没问题，但是出现了播放控件3秒自动隐藏后光标色块遮挡了整个画面的问题，就像画面上层覆盖了一个半透明紫色遮罩一样，如果点击返回使光标重新聚焦于某个空间元素时画面遮罩消失，但是过几秒控件自动隐藏了遮罩就又回画面上了
补充一下，该情况在使用触控操作时不存在，只有使用遥控器时才有，即使因为使用遥控器操作有了这个遮挡画面的遮罩，用触控方式点一下屏幕也会消失

**Comment by xiaye13579** [comment]
1.1.5会修复这个问题

**Comment by fox0517** [comment]
大佬太优秀了，复测已解决
