### ISSUE TITLE
关于前进和后退的问题

### ISSUE THREAD

**Issue by AzureZH** [xiaye13579/BBLL#73]
首先感谢大佬开发了这么一个简单易用功能强大的客户端
但在最近的使用时发现了一个问题，快进和后退似乎是按照视频时长的百分比来计算的，在看有些时间比较长视频的时候，前进或者后退一次就跳过了几十秒，有些时候只想回看刚过去的一个镜头，但因为回退过多，就要等很长时间。
能否将一次前进和后退的时值固定设定为5秒或者10秒，发现用户长按按键打算长时间跳过的时候再根据按键时间的长短来检索时间线？
非常感谢开发者的劳动，希望本客户端越做越好

**Comment by AzureZH** [comment]
还有就是之前的issue里有人提到过的问题，建议把播放时的左右键和确定键直接设定为前进后退和暂停功能，上下键设定为选P和推荐视频功能。其他功能由菜单键唤醒UI再进行具体的详细操作

**Comment by xiaye13579** [comment]
1.1.6设置里可以打开快进快退按钮，快进以15s为单位
