### ISSUE TITLE
无法登入

### ISSUE THREAD

**Issue by Jay-Young** [xiaye13579/BBLL#907]
1.4.9刚掉登录了，点登录二维码无法显示，一直转圈圈。点其他方式用手机号可以登录成功，但是登录成功后跳转后还是显示需要登录。此时再点其他方式登录直接返回，无法再次登录。看b站官方app设备里电视确实是已经登录状态。卸载重装与清缓存无效。https://github.com/xiaye13579/BBLL/assets/8641055/0efadb9c-4c5f-4650-a7ac-d05196be5ac1

**Comment by 188198** [comment]
校对下设备时间试试，安卓盒子时间不准也出现过这问题，时间调好后正常了
