### ISSUE TITLE
海信电视不兼容

### ISSUE THREAD

**Issue by dongxue88815** [xiaye13579/BBLL#918]
![image](https://github.com/xiaye13579/BBLL/assets/57471836/887df2af-c13d-4147-8ee5-7f12dbfcd97a)
网上有修改版，期待大佬更新下，虽然可以用任务切换进入，使用不够丝滑

**Comment by dongxue88815** [comment]
> ![image](https://private-user-images.githubusercontent.com/57471836/301001856-887df2af-c13d-4147-8ee5-7f12dbfcd97a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MDI4OTMsIm5iZiI6MTcwNzcwMjU5MywicGF0aCI6Ii81NzQ3MTgzNi8zMDEwMDE4NTYtODg3ZGYyYWYtYzEzZC00MTQ3LThlZTUtN2YxMmRiZmNkOTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAxNDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNDZjMDZmNGQ3N2YxYWZjYzgwYjU4NWY2Nzc5MDg4NTQxZTY5Mzg0YzA3ODQ5MWRlMzMyYTQyMjIyNWViNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.boA0tzE7PYDdBaXsw1tTHLz9aXQihOUQNrYRhl-SQEc) 网上有修改版，期待大佬更新下，虽然可以用任务切换进入，使用不够丝滑

**Comment by ECS-tasy** [comment]
存在风险的话可以试试用adb的方式装
