### ISSUE TITLE
希望添加H.264解码方式，拯救一下老电视。

### ISSUE THREAD

**Issue by ctrl-s-i** [xiaye13579/BBLL#93]
希望添加H.264解码方式，拯救一下老电视。

**Comment by Ezukki** [comment]
大哥 咱发issues之前 能不能动动脑子 自己去电视实测一下 或者百度搜一下 avc就是h.264 hevc就是h.265 群里人都快笑疯了看到你这个issues 我真的纯属好心回复一下 下次没搞清楚之前别乱提issues
