### ISSUE TITLE
[功能请求] 支持遥控器的“下一个”、“上一个”按键

### ISSUE THREAD

**Issue by chuwza** [xiaye13579/BBLL#930]
大佬你好，非常感谢你的BBLL，安卓电视体验好很多~

但是目前有个问题：UI界面上的上一个、下一个按键并不能通过遥控器来操控，希望能支持遥控器。
![screenshot_1707531877141z](https://github.com/xiaye13579/BBLL/assets/30049891/123a69a1-2ef9-4ab5-98cc-bcb5fb05d320)

隔壁第三方YouTube客户端[SmartTube](https://github.com/yuliskov/SmartTube)就支持通过遥控来进行上一个、下一个操作。

BBLL做为一个电视软件，个人还是非常希望能完全适配遥控器的

**Comment by chuwza** [comment]
> 大佬你好，非常感谢你的BBLL，安卓电视体验好很多~
> 
> 但是目前有个问题：UI界面上的上一个、下一个按键并不能通过遥控器来操控，希望能支持遥控器。 ![screenshot_1707531877141z](https://private-user-images.githubusercontent.com/30049891/303809385-123a69a1-2ef9-4ab5-98cc-bcb5fb05d320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzM2OTQsIm5iZiI6MTcwNzYzMzM5NCwicGF0aCI6Ii8zMDA0OTg5MS8zMDM4MDkzODUtMTIzYTY5YTEtMmVmOS00YWI1LTk4Y2MtYmNiNWZiMDVkMzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA2MzYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMzM4ZmI3YTcwNDhiOWZiYTI5MjZlNjU5NzRlYzM3NmE3ZjhiZDk4YjgyNjQ2ZTUwZmIzYmU3NGJiNTNiN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nZvqQcKOvMWgocciQg3WhFmWGoN9ia4O_Pb14yOutY)
> 
> 隔壁第三方YouTube客户端[SmartTube](https://github.com/yuliskov/SmartTube)就支持通过遥控来进行上一个、下一个操作。
> 
> BBLL做为一个电视软件，个人还是非常希望能完全适配遥控器的

我发现Android TV上有两种上一个下一个，普通的一种BBLL不支持，但另一种按键映射的是支持的，但是另一种按键映射的需要复杂设置甚至Root，所以还是希望支持普通的上一个下一个、快进快退

**Comment by wangxufire** [comment]
+1
