### ISSUE TITLE
今天所有视频都显示source error, 能刷新能登录, 但是所有视频都无法播放

### ISSUE THREAD

**Issue by sirlioniva** [xiaye13579/BBLL#996]
1.4.9版本,国行索尼安卓10系统

打开视频的时候弹幕也可以正常加载,但是视频就是source error

是否和大会员到期清晰度下降有关?

因为这几天大会员刚好到期,有一次弹出该分辨率需要大会员,我就在设置里直接把分辨率调到720p

现在就打不开任何视频了, 两者中间是否能播放我已经忘记, 现在没有大会员我只能选720但是所有视频都无法播放

**Comment by sirlioniva** [comment]
居然是被adgh杀了,但是手机app和网页版都正常

**Comment by francisic** [comment]
我的设备上此问题也很严重。

**Comment by MaxWill-H** [comment]
我也是同意的问题
